#Настройка цвета
death-message-color: "<yellow>"

#Список всех сообщений о смерти
death-attack-anvil: "%1 раздавлен упавшей наковальней"
death-attack-anvil-player: "%1 был раздавлен упавшей наковальней, пока боролся с %2"
death-attack-arrow: "%1 застрелен %2"
death-attack-arrow-item: "%1 застрелен %2 с помощью %3"
death-attack-badRespawnPoint-link: "жестоких правил игры"
death-attack-badRespawnPoint-message: "%1 стал жертвой %2"
death-attack-cactus: "%1 исколот до смерти"
death-attack-cactus-player: "%1 наткнулся на кактус, спасаясь от %2"
death-attack-cramming: "%1 расплющен в лепёшку"
death-attack-cramming-player: "%1 расплющен %2"
death-attack-dragonBreath: "%1 растворился в драконьем дыхании"
death-attack-dragonBreath-player: "%1 сварился заживо в драконьем дыхании из-за %2"
death-attack-drown: "%1 утонул"
death-attack-drown-player: "%1 утонул, спасаясь от %2"
death-attack-dryout: "%1 умер от обезвоживания"
death-attack-dryout-player: "%1 умер от обезвоживания, спасаясь от %2"
death-attack-even_more_magic: "%1 был убит неизведанной магией"
death-attack-explosion: "%1 взорвался"
death-attack-explosion-player: "%1 был взорван %2"
death-attack-explosion-player-item: "%1 был взорван %2 с помощью %3"
death-attack-fall: "%1 разбился вдребезги"
death-attack-fall-player: "%1 разбился вдребезги, спасаясь от %2"
death-attack-fallingBlock: "%1 раздавлен упавшим блоком"
death-attack-fallingBlock-player: "%1 был раздавлен упавшим блоком, пока боролся с %2"
death-attack-fallingStalactite: "%1 был пронзён обрушившимся сталактитом"
death-attack-fallingStalactite-player: "%1 был пронзён обрушившимся сталактитом, пока боролся с %2"
death-attack-fireball: "%1 убит файерболом %2"
death-attack-fireball-item: "%1 убит файерболом %2 с помощью %3"
death-attack-fireworks: "%1 с треском разлетелся"
death-attack-fireworks-item: "%1 с треском разлетелся из-за фейерверка %2, выпущенного из %3"
death-attack-fireworks-player: "%1 с треском разлетелся, пока боролся с %2"
death-attack-flyIntoWall: "%1 преобразовал кинетическую энергию во внутреннюю"
death-attack-flyIntoWall-player: "%1 преобразовал кинетическую энергию во внутреннюю, спасаясь от %2"
death-attack-freeze: "%1 замёрз насмерть"
death-attack-freeze-player: "%1 замёрз насмерть благодаря %2"
death-attack-generic: "%1 умер"
death-attack-generic-player: "%1 умер из-за %2"
death-attack-hotFloor: "%1 обнаружил, что пол — это лава"
death-attack-hotFloor-player: "%1 зашёл в опасную зону из-за %2"
death-attack-inFire: "%1 умер в огне"
death-attack-inFire-player: "%1 сгорел в огне, пока боролся с %2"
death-attack-inWall: "%1 погребён заживо"
death-attack-inWall-player: "%1 был погребён заживо, пока боролся с %2"
death-attack-indirectMagic: "%1 был убит %2 с помощью магии"
death-attack-indirectMagic-item: "%1 был убит %2 с помощью %3"
death-attack-lava: "%1 решил поплавать в лаве"
death-attack-lava-player: "%1 упал в лаву, убегая от %2"
death-attack-lightningBolt: "%1 был поражён молнией"
death-attack-lightningBolt-player: "%1 был поражён молнией, пока боролся с %2"
death-attack-magic: "%1 был убит магией"
death-attack-magic-player: "%1 был убит магией, спасаясь от %2"
death-attack-message_too_long: "Сообщение слишком длинное для доставки. Извините! Вот сокращённая версия: %s"
death-attack-mob: "%1 был убит %2"
death-attack-mob-item: "%1 был убит %2 с помощью %3"
death-attack-onFire: "%1 сгорел заживо"
death-attack-onFire-item: "%1 был поджарен, пока боролся с %2, с помощью %3"
death-attack-onFire-player: "%1 был сожжён дотла, пока боролся с %2"
death-attack-outOfWorld: "%1 выпал из мира"
death-attack-outOfWorld-player: "%1 не захотел жить в том же мире, что и %2"
death-attack-player: "%1 был убит %2"
death-attack-player-item: "%1 был убит %2 с помощью %3"
death-attack-sonic_boom: "%1 был уничтожен звуковым зарядом"
death-attack-sonic_boom-item: "%1 был уничтожен звуковым зарядом, спасаясь от %2 c %3"
death-attack-sonic_boom-player: "%1 был уничтожен звуковым ударом, спасаясь от %2"
death-attack-stalagmite: "%1 пронзён сталагмитом"
death-attack-stalagmite-player: "%1 был пронзён сталагмитом, пока боролся с %2"
death-attack-starve: "%1 умер от голода"
death-attack-starve-player: "%1 умер от голода, пока боролся с %2"
death-attack-sting: "%1 изжален до смерти"
death-attack-sting-item: "%1 был изжален до смерти %2 с помощью %3"
death-attack-sting-player: "%1 изжален до смерти %2"
death-attack-sweetBerryBush: "%1 искололся до смерти в кустах сладких ягод"
death-attack-sweetBerryBush-player: "%1 искололся до смерти в кустах сладких ягод, спасаясь от %2"
death-attack-thorns: "%1 был убит, пытаясь навредить %2"
death-attack-thorns-item: "%1 был убит %3, пытаясь навредить %2"
death-attack-thrown: "%1 был избит %2"
death-attack-thrown-item: "%1 был избит %2 с помощью %3"
death-attack-trident: "%1 был пронзён %2"
death-attack-trident-item: "%1 пронзён %2 с помощью %3"
death-attack-wither: "%1 иссушён"
death-attack-wither-player: "%1 был иссушён, пока боролся с %2"
death-attack-witherSkull: "%1 был поражён черепом из %2"
death-attack-witherSkull-item: "%1 был поражён черепом из %2 с помощью %3"
death-fell-accident-generic: "%1 разбился насмерть"
death-fell-accident-ladder: "%1 свалился с лестницы"
death-fell-accident-other_climbable: "%1 сорвался"
death-fell-accident-scaffolding: "%1 сорвался с подмосток"
death-fell-accident-twisting_vines: "%1 сорвался с вьющейся лозы"
death-fell-accident-vines: "%1 сорвался с лианы"
death-fell-accident-weeping_vines: "%1 сорвался с плакучей лозы"
death-fell-assist: "%1 свалился благодаря %2"
death-fell-assist-item: "%1 был обречён на падение %2 с помощью %3"
death-fell-finish: "%1 упал с высоты и был добит %2"
death-fell-finish-item: "%1 упал с высоты и был добит %2 с помощью %3"
death-fell-killer: "%1 был обречён на падение"